name: Dependency Review

on:
  pull_request:

jobs:
  review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
